
from pyvisdk.do.dynamic_data import DynamicData
import logging

########################################
# Automatically generated, do not edit.
########################################

log = logging.getLogger(__name__)

class ClusterDrsFaultsFaultsByVm(DynamicData):
    '''FaultsByVm is the faults generated by DRS when it tries to move a VM.
    '''
    
    def __init__(self, fault, vm):
        # MUST define these
        super(ClusterDrsFaultsFaultsByVm, self).__init__()
    
        self.data['fault'] = fault
        self.data['vm'] = vm
    
    
    @property
    def fault(self):
        '''The faults generated by DRS when it was trying to move the given VM.
        '''
        return self.data['fault']

    @property
    def vm(self):
        '''The VM that DRS was trying to migrate when it generated the faults. If this field
        is NULL, the fault is not associated with a particular VM.
        '''
        return self.data['vm']

