
from pyvisdk.do.dynamic_data import DynamicData
import logging

########################################
# Automatically generated, do not edit.
########################################

log = logging.getLogger(__name__)

class ClusterDrsFaults(DynamicData):
    '''The faults generated by DRS when it tries to make recommendations for rule
        enforcement, power management, etc., and indexed in a tree structure with
        reason for recommendations and VM to migrate (optional) as the index keys.
    '''
    
    def __init__(self, faultsByVm, reason):
        # MUST define these
        super(ClusterDrsFaults, self).__init__()
    
        self.data['faultsByVm'] = faultsByVm
        self.data['reason'] = reason
    
    
    @property
    def faultsByVm(self):
        '''The faults grouped by VMs that DRS was trying to migrate.
        '''
        return self.data['faultsByVm']

    @property
    def reason(self):
        '''A reason code explaining why this set of recommendations were attempted by DRS
        when it generated the faults.
        '''
        return self.data['reason']

