
from pyvisdk.do.customization_name import CustomizationName
import logging

########################################
# Automatically generated, do not edit.
########################################

log = logging.getLogger(__name__)

class CustomizationPrefixName(CustomizationName):
    '''Specifies that a unique name should be generated by concatenating the base string
        with a number.Virtual machine names are unique across the set of hosts and
        virtual machines known to the VirtualCenter instance. VirtualCenter tracks
        the network names of virtual machines as well as hosts. VMware Tools runs
        in a guest operating system and reports information to VirtualCenter,
        including the network name of the guest.
    '''
    
    def __init__(self, base):
        # MUST define these
        super(CustomizationPrefixName, self).__init__()
    
        self.data['base'] = base
    
    
    @property
    def base(self):
        '''Base prefix, to which a unique number is appended.
        '''
        return self.data['base']

