# -*- coding: ascii -*-

import logging

########################################
# Automatically generated, do not edit.
########################################

log = logging.getLogger(__name__)

def CustomizationPrefixName(vim, *args, **kwargs):
    '''Specifies that a unique name should be generated by concatenating the base
    string with a number.Virtual machine names are unique across the set of hosts
    and virtual machines known to the VirtualCenter instance. VirtualCenter tracks
    the network names of virtual machines as well as hosts. VMware Tools runs in a
    guest operating system and reports information to VirtualCenter, including the
    network name of the guest.'''
    
    obj = vim.client.factory.create('ns0:CustomizationPrefixName')
    
    # do some validation checking...
    if (len(args) + len(kwargs)) < 1:
        raise IndexError('Expected at least 0 arguments got: %d' % len(args))
        
    args_list = [ 'base' ]
    
    for name, arg in zip(args_list, args):
        setattr(obj, name, arg)
    
    for name, value in kwargs.items():
        setattr(obj, name, value)

    return obj
    