
from pyvisdk.do.dynamic_data import DynamicData
import logging

########################################
# Automatically generated, do not edit.
########################################

log = logging.getLogger(__name__)

class IpPool(DynamicData):
    '''Specifications of the network configuration to be used on a network. This is used
        to generate IP addresses and for self-customization of vApps.
    '''
    
    def __init__(self, dnsDomain, dnsSearchPath, hostPrefix, httpProxy, id, ipv4Config, ipv6Config, name, networkAssociation):
        # MUST define these
        super(IpPool, self).__init__()
    
        self.data['dnsDomain'] = dnsDomain
        self.data['dnsSearchPath'] = dnsSearchPath
        self.data['hostPrefix'] = hostPrefix
        self.data['httpProxy'] = httpProxy
        self.data['id'] = id
        self.data['ipv4Config'] = ipv4Config
        self.data['ipv6Config'] = ipv6Config
        self.data['name'] = name
        self.data['networkAssociation'] = networkAssociation
    
    
    @property
    def dnsDomain(self):
        '''DNS Domain. For example, vmware.com. This can be an empty string if no domain is
        configured.
        '''
        return self.data['dnsDomain']

    @property
    def dnsSearchPath(self):
        '''DNS Search Path. For example, eng.vmware.com;vmware.com
        '''
        return self.data['dnsSearchPath']

    @property
    def hostPrefix(self):
        '''Prefix for hostnames.
        '''
        return self.data['hostPrefix']

    @property
    def httpProxy(self):
        '''The HTTP proxy to use on this network, e.g., :
        '''
        return self.data['httpProxy']

    @property
    def id(self):
        '''Unique ID, generated by the server. This is used to identify the pool in
        subsequent lookups or updates. The generated value is also returned by the
        CreateIpPool method.
        '''
        return self.data['id']

    @property
    def ipv4Config(self):
        '''IPv4 configuration.
        '''
        return self.data['ipv4Config']

    @property
    def ipv6Config(self):
        '''IPv6 configuration.
        '''
        return self.data['ipv6Config']

    @property
    def name(self):
        '''Pool name. Must be unique.
        '''
        return self.data['name']

    @property
    def networkAssociation(self):
        '''The networks that are associated with this IP pool
        '''
        return self.data['networkAssociation']

